### ISSUE TITLE
"Display privacy policy on startup" deactivates automatically while going back to the app.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [JohnLines/mediclog#14]
#### Expected behavior
On going to preference section while activating "Display privacy policy on startup" 
, it must be activated until it will be deactivated. 
#### Actual behaviour
While acyivating the "Display privacy policy on startup" it must activated until it will be deactivated. But while going back to home page of app it gets automatically deactivated. 

#### How to reproduce
Open the app. 

Go to preference section by clicking on the three dots on right top corner of app. 

Activate the "Display privacy policy on startup". 

Go back to home page of app. 

Then go again to the preference section. 

It automatically gets deactivated. 

* Browser: Medic log
* Version:0.2.1
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/CcDIGz1a0So
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/bug-found-in-medic-log">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JohnLines** [comment]
Most apps only display their privacy policy when they are first run, and probably then only because Google Apps policy requires this for applications handling private data. I had assumed most users would not wish to be reminded of the Medic Log privacy policy, which can be summarised as "Your data is yours, and you decide who to share it with".

There would be less indignation about certain social media apps if, every time they were run, the user had to accept sharing all their contact information, their location, send and recieve SMS messages, use their camera and microphone, read and write to their storage etc (see the Permissions info in your favourite app and compare it with the permissions available to Medic Log (currently none).

I will work to accommodate your request and would encourage developers of apps where privacy really is an issue to follow suite.

**Comment by JohnLines** [comment]
There is a new preferences item - Display Privacy Policy on each startup, which will display the Privacy Policy every time the app starts. This is not cleared by the Accept Button, and will be set by the Accept Keep button.

**Comment by JohnLines** [comment]
Closed in 0.2.2
